### Get All Contents
GET http://localhost:8080/api/contents

### Get a content by ID
GET http://localhost:8080/api/{id}

### Create a new content
POST http://localhost:8080/api/contents/create
Content-Type: application/json

{
  "id": 4,
  "title": "jol",
  "desc" : "My fourth blog post",
  "status": "COMPLETED",
  "contentType": "VIDEO",
  "createdAt": "2023-02-13T10:25:02",
  "updatedAt": "2023-02-13T10:25:02",
  "url": ""
}


### Update an exisitng content
PUT http://localhost:8080/api/contents/update/1
Content-Type: application/json

{
  "id": 1,
  "title": "Get me my funds",
  "desc" : "My fourth blog post",
  "status": "COMPLETED",
  "contentType": "VIDEO",
  "createdAt": "2023-02-13T10:25:02",
  "updatedAt": null,
  "url": ""
}

### Delete a content
DELETE http://localhost:8080/api/contents/delete/1